### ISSUE TITLE
gradle导入dialog

### ISSUE THREAD

**Issue by chenyacheng** [senonwx/mvpretrofitrx#1]
非常谢谢你开源这个项目，让我发现了它，你写的很不错，我正你的这个项目来拓展我的项目。我发现一个问题，我用的android studio是3.0以上的，在gradle导入dialog的时候项目跑起来，用到dialog的时候报错(compile 'cn.pedant.sweetalert:library:1.3')，我换了另一种导入方式：compile 'com.github.f0ris.sweetalert:library:1.5.1'，就没问题了。

**Comment by lixiaopengaxn** [comment]
@yacheng199306 是不是人吧类库名字换了，#24，

**Comment by chenyacheng** [comment]
这个我就不清楚了

**Comment by senonwx** [comment]
可能是引用的仓库不一样，我用的是jcenter()，google()，maven { url "https://jitpack.io" }是没有问题的

**Comment by lixiaopengaxn** [comment]
thanks




    
    
        
            
                
                    
                        
                    
                    
                        
                            bzzguo
                            
                            
                                
                                    邮箱：bzzguo@qq.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年08月31日 23:57，senonwx 写道： 可能是引用的仓库不一样，我用的是jcenter()，google()，maven { url "https://jitpack.io" }是没有问题的

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/senonwx/mvpretrofitrx","title":"senonwx/mvpretrofitrx","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/senonwx/mvpretrofitrx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@senonwx in #1: 可能是引用的仓库不一样，我用的是jcenter()，google()，maven { url \"https://jitpack.io\" }是没有问题的"}],"action":{"name":"View Issue","url":"https://github.com/senonwx/mvpretrofitrx/issues/1#issuecomment-417709388"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/senonwx/mvpretrofitrx/issues/1#issuecomment-417709388",
"url": "https://github.com/senonwx/mvpretrofitrx/issues/1#issuecomment-417709388",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [senonwx/mvpretrofitrx] gradle导入dialog (#1)",
"sections": [
{
"text": "",
"activityTitle": "**senonwx**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@senonwx",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"senonwx/mvpretrofitrx\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"senonwx/mvpretrofitrx\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/senonwx/mvpretrofitrx/issues/1#issuecomment-417709388"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 291444053\n}"
}
],
"themeColor": "26292E"
}
]
